spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    default: local

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect